---
language: go
go:
- 1.9.x

sudo: required

services:
  - docker

notifications:
  email:
    on_success: never
    on_failure: change

env:
  - DEP_VERSION="0.4.1"

cache:
  directories:
  - vendor

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker --version # for verification
  - go get -u github.com/goreleaser/goreleaser

install:
  - dep ensure

after_success:
  - if [ -n "$TRAVIS_TAG" ]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      goreleaser --rm-dist;
    fi
