---
language: go
go:
- 1.9.x

sudo: required

services:
  - docker

notifications:
  email:
    on_success: never
    on_failure: change

env:
  - DEP_VERSION="0.3.2"

cache:
  directories:
  - vendor

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker --version # for verification

install:
  - dep ensure

after_success:
  - if [ -n "$TRAVIS_TAG" ]; then
      echo "Building version ${TRAVIS_TAG}...";
      docker build -t neckhair/crontainer:latest .;

      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      docker tag neckhair/crontainer:latest neckhair/crontainer:${TRAVIS_TAG};
      docker push neckhair/crontainer:latest;
      docker push neckhair/crontainer:${TRAVIS_TAG};
    fi
